[workspace]
resolver = "2"
members = [
    "crates/genies",
    "crates/genies_derive"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["tdcare"]
license = "MIT"
repository = "https://github.com/tdcare/genies"