#debug模式，true输出控制台日志，false只输出文件日志.生产环境需要关闭debug，rbatis也需移除"debug_mode"
debug: true #true #false

#微服务名称
server_name: "baseinfo-service"

#微服务的路由前缀，对应 java application.properties 配置文件中的 spring.mvc.servlet.path。
servlet_path: "/baseinfo"

#server 地址
server_url: "0.0.0.0:8011"

#用于指定gateway 如果指定了gateway 为合法的 http 协议(以http:// 或 https:// 开头) 所有跨微访问都将通 gateway 进行
#如果gateway 为非法的http 协议 将通Dapr 方式进行访问
gateway:  "http://58.20.184.66:6015"

#缓存介质类型,单选("mem","redis")
cache_type: "redis"

#redis地址(cache_type为“redis”时有效)
redis_url: "redis://:reCtfK2_CK8tAjLU@redis-service:6007"

#可持久化redis地址(cache_type为“redis”时有效)
redis_save_url: "redis://:reCtfK2_CK8tAjLU@redis-save-service:6007"

#数据库地址   root:root@127.0.0.1:3306/baseinfo_service
database_url: "mysql://tdnis:Tdcare123for$@58.20.184.66:6006/baseinfo_service?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8"

#数据库连接池参数
max_connections: 20
min_connections: 0
wait_timeout: 60
max_lifetime: 1800
create_timeout: 120

##日志文件存放目录
#log_dir: "log/"
##日志通道最大缓存日志条数
#log_cup: 50
##日志分割尺寸-单位KB,MB,GB
#log_temp_size: "100MB"
##日志打包格式可选“”（空-不压缩）“gzip”（gz压缩包）“zip”（zip压缩包）“lz4”（lz4压缩包（非常快））
#log_pack_compress: "zip"
##日志滚动保留-保留全部: All,按时间保留(秒): KeepTime(i64),按版本保留: KeepNum(i64)
#log_rolling_type: "All"
##日志等级-info,error,warn,debug,trace
log_level: "debug"

# keycloak 参数
#keycloak_auth_server_certs: "http://122.9.125.181/auth/realms/tdcare/protocol/openid-connect/certs"
keycloak_auth_server_url: "http://58.20.184.66:6015/auth/"
keycloak_realm: "tdcare"
keycloak_resource: "tdnis"
keycloak_credentials_secret: "701ef8cd-43b9-407e-80df-0dfc96c461dc"

## Dapr http 端口
#dapr_http_port: 3500
#dapr_http: http://localhost:3500
#
#Dapr cdc 参数
dapr_pubsub_name: messagebus
#每次投递消息的数量
dapr_pub_message_limit: 50
#time::Duration::from_millis(dapr_cdc_message_period);
dapr_cdc_message_period: 5000

#处理消息 最长的时间 单位 秒
processing_expire_seconds: 60
#消息处理成功后，状态保存的最长时间 单位 分钟
record_reserve_minutes: 10080

#是否通过轮询的方式回写 现在仅仅衡阳中心医院通过轮询的方式实现
isPollWrite: 0

printFlag: 1

#接口白名单（免登陆直接访问）
white_list_api:
 - "/"
 - "/actors/*"
 - "/actuator/*"
 - "/dapr/*"
 - "/system/*"
 - "/daprsub/*"
 - "/daprsub"


