
FROM clux/muslrust:stable AS builder
USER root
WORKDIR /rfcbot
RUN rustup component add rustfmt

COPY . .
RUN   cargo build  --release --target x86_64-unknown-linux-musl


# Need cacerts
FROM alpine:3.16.0
RUN apk add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata
COPY --from=builder  /rfcbot/target/x86_64-unknown-linux-musl/release/cdc /
COPY application.yml /
EXPOSE 8010
CMD ["/cdc"]