pub mod user_repository;
pub mod role_repository;
pub mod permission_repository;
pub mod department_repository;
pub mod user_department_repository;
pub mod application_repository;
pub mod app_instance_repository;
pub mod settings_repository;
pub mod user_2fa_repository;
