-- Casbin 策略规则表
-- 存储 RBAC 权限策略、角色分配、对象分组等规则
CREATE TABLE IF NOT EXISTS casbin_rules (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    ptype VARCHAR(16) NOT NULL,
    v0 VARCHAR(256) NOT NULL DEFAULT '',
    v1 VARCHAR(256) NOT NULL DEFAULT '',
    v2 VARCHAR(256) NOT NULL DEFAULT '',
    v3 VARCHAR(256) NOT NULL DEFAULT '',
    v4 VARCHAR(256) NOT NULL DEFAULT '',
    v5 VARCHAR(256) NOT NULL DEFAULT '',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
